export const FEES_MASTER = {
  HEADER: "Add Installment",
  FORM_HEADER: "Add Installment form",
  DISPLAY_INSTALLMENT_HEADER: "Installments",
  PLACEHOLDER_INSTALLMENT_NAME: 'Installment Name*',
  PLACEHOLDER_INSTALLMENT_AMOUNT: 'Installment Amount*',
  PLACEHOLDER_SELECT_CLASS: 'Select Class*',
  INSTALLMENT_NAME_ROW_HEADER: 'Installment',
  INSTALLMENT_AMOUNT_ROW_HEADER: 'Amount',
  INSTALLMENT_ACTION_ROW_HEADER: 'Action',
  ADD_BUTTON_LABEL: 'Add',
  UPDATE_BUTTON_LABEL: 'Update',
};
